// Copyright (c) 2026 haitch
// Licensed under the Apache License, Version 2.0
// https://www.apache.org/licenses/LICENSE-2.0

package storage

import "context"

// QueryCapabilities reports what a storage backend can handle natively
// via predicate push-down. Used by the OQL planner to decide which
// operations to delegate to the storage engine versus executing in Go.
type QueryCapabilities struct {
	Where   bool // Can filter with json_extract predicates
	OrderBy bool // Can sort by json_extract fields
	Limit   bool // Can apply TOP/LIMIT
	Count   bool // Can return entity count without full scan
}

// Queryable is an optional interface for storage backends that support
// predicate push-down. Backends that do not implement it receive the
// full Go-side execution path for all operations.
//
// The OQL planner checks for this interface via type assertion. If the
// store satisfies Queryable and the entity cardinality exceeds the
// push-down threshold, the planner may generate SQL to delegate WHERE,
// ORDER BY, and LIMIT operations to the storage engine.
type Queryable interface {
	// Capabilities reports which query operations this backend handles
	// natively. The planner will not attempt to push down an operation
	// unless the corresponding capability is true.
	Capabilities() QueryCapabilities

	// CountEntities returns the number of records for an entity type
	// without fetching the records themselves. Used by the planner to
	// determine whether push-down is worthwhile (the fixed overhead of
	// a push-down query exceeds Go-side cost for small datasets).
	CountEntities(ctx context.Context, entity string) (int, error)

	// QueryWithPlan executes a pre-built SQL query with parameterised
	// arguments and returns the results as maps, in the same format as
	// List(). The SQL is generated by the OQL planner's SQL generator
	// and always selects from the data column with json_extract().
	QueryWithPlan(ctx context.Context, sql string, args []interface{}) ([]map[string]interface{}, error)
}
